settings:
  APP_DISPLAY_NAME: Privox
  PRODUCTION_APP_NAME: Privox
  APP_GROUP_IDENTIFIER: group.im.privox.app
  BASE_BUNDLE_IDENTIFIER: im.privox.app
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: RP839MT6BR

  # Optional configuration to load accounts from Element Classic.
  CLASSIC_APP_GROUP_IDENTIFIER: group.im.privox.app
  CLASSIC_APP_KEYCHAIN_SERVICE_IDENTIFIER: im.privox.app.encryption-manager-service
  CLASSIC_APP_KEYCHAIN_ACCESS_GROUP_IDENTIFIER: "$(DEVELOPMENT_TEAM).im.privox.app.keychain.shared"
